---
name: CI
on: [push]
jobs:
  ci:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: [1.12, 1.13]
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Prepare
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update -q && sudo apt-get install -qqy libpcsclite-dev
      - name: Check
        run: go test -cover ./...
...
